font_family        CodeNewRoman Nerd Font Mono
bold_font          auto
italic_font        auto
bold_italic_font   auto

font_size        9
enable_audio_bell no

shell_integration no-cursor
cursor_shape block

hide_window_decorations yes

# Cursor animation
# cursor_trail                   3
# cursor_trail_decay             0.05 0.15
# cursor_trail_start_threshold   0


# BEGIN_KITTY_THEME
# Gruvbox Dark
# include current-theme.conf
# END_KITTY_THEME

# Path to your background image (Must be in PNG format)
background_image ~/Pictures/rate-my-setup-xfce-v0-h9pd2gw3hvsh1.png

# How the image should be displayed (clamped, mirrored, tiled, scaled, or cscaled)
background_image_layout scaled

# Control the image opacity (0.0 fully transparent, 1.0 fully opaque)
# Adjust this so you can still read your terminal text clearly!
background_image_linear yes

background_tint 0.95

# # A value between 0.0 (fully transparent) and 1.0 (fully opaque)
# background_opacity 0.85
#
# # Optional: Add blur to the background text (macOS / some Linux compositors)
# background_blur 32
